#!/bin/bash
# DocuForge Engine API Demo
# Run the server first: make run (or cargo run)

set -e

BASE_URL="${DOCUFORGE_URL:-http://localhost:3001}"
OUTPUT_DIR="${OUTPUT_DIR:-./pdfs}"

mkdir -p "$OUTPUT_DIR"

echo "=========================================="
echo "DocuForge Engine API Demo"
echo "=========================================="
echo "Base URL: $BASE_URL"
echo "Output Directory: $OUTPUT_DIR"
echo ""

# Health Check
echo "1. Health Check"
echo "---------------"
curl -s "$BASE_URL/health" | jq .
echo ""

# Simple Hello World
echo "2. Simple Hello World PDF"
echo "--------------------------"
curl -s -X POST "$BASE_URL/render" \
  -H "Content-Type: application/json" \
  -d '{
    "template": {
      "main": "main.typ",
      "files": {
        "main.typ": "= Hello World\n\nThis is a simple PDF generated by DocuForge Engine."
      }
    }
  }' \
  --output "$OUTPUT_DIR/01-hello-world.pdf"
echo "Generated: $OUTPUT_DIR/01-hello-world.pdf"
file "$OUTPUT_DIR/01-hello-world.pdf"
echo ""

# With Data Substitution
echo "3. Data Substitution"
echo "--------------------"
curl -s -X POST "$BASE_URL/render" \
  -H "Content-Type: application/json" \
  -d '{
    "template": {
      "main": "main.typ",
      "files": {
        "main.typ": "#let d = sys.inputs\n\n= Welcome, #d.name!\n\nYour account balance is *$#d.balance*.\n\nMembership: #d.membership"
      }
    },
    "data": {
      "name": "John Doe",
      "balance": 1234.56,
      "membership": "Gold"
    }
  }' \
  --output "$OUTPUT_DIR/02-data-substitution.pdf"
echo "Generated: $OUTPUT_DIR/02-data-substitution.pdf"
echo ""

# Invoice Template
echo "4. Invoice Template"
echo "-------------------"
curl -s -X POST "$BASE_URL/render" \
  -H "Content-Type: application/json" \
  -d '{
    "template": {
      "main": "main.typ",
      "files": {
        "main.typ": "#let d = sys.inputs\n#set page(paper: \"a4\", margin: 2cm)\n#set text(size: 11pt)\n\n#align(center)[#text(size: 24pt, weight: \"bold\")[INVOICE]]\n\n#v(1cm)\n\n#grid(columns: (1fr, 1fr), gutter: 2cm,\n  [\n    *From:*\\\n    #d.company.name\\\n    #d.company.address\n  ],\n  [\n    *Invoice:* ##d.invoice_number\\\n    *Date:* #d.date\\\n    *Due:* #d.due_date\n  ]\n)\n\n#v(1cm)\n\n*Bill To:*\\\n#d.customer.name\\\n#d.customer.address\n\n#v(1cm)\n\n#table(\n  columns: (auto, 1fr, auto, auto, auto),\n  inset: 8pt,\n  align: (center, left, right, right, right),\n  [*#*], [*Description*], [*Qty*], [*Price*], [*Total*],\n  ..d.items.enumerate().map(((i, item)) => (\n    str(i + 1),\n    item.description,\n    str(item.quantity),\n    [\\$#item.price],\n    [\\$#calc.round(item.quantity * item.price, digits: 2)]\n  )).flatten()\n)\n\n#v(0.5cm)\n#align(right)[\n  #table(\n    columns: (auto, auto),\n    stroke: none,\n    inset: 4pt,\n    [Subtotal:], [\\$#d.subtotal],\n    [Tax (#d.tax_rate%):], [\\$#d.tax],\n    [*Total:*], [*\\$#d.total*]\n  )\n]"
      }
    },
    "data": {
      "invoice_number": "INV-2024-001",
      "date": "2024-01-15",
      "due_date": "2024-02-15",
      "company": {
        "name": "DocuForge Inc.",
        "address": "123 Tech Street, San Francisco, CA 94102"
      },
      "customer": {
        "name": "Acme Corporation",
        "address": "456 Business Ave, New York, NY 10001"
      },
      "items": [
        {"description": "Web Development Services", "quantity": 40, "price": 150},
        {"description": "UI/UX Design", "quantity": 20, "price": 125},
        {"description": "Server Setup & Configuration", "quantity": 8, "price": 200},
        {"description": "Monthly Hosting", "quantity": 12, "price": 50}
      ],
      "subtotal": 9700,
      "tax_rate": 8.5,
      "tax": 824.50,
      "total": 10524.50
    }
  }' \
  --output "$OUTPUT_DIR/03-invoice.pdf"
echo "Generated: $OUTPUT_DIR/03-invoice.pdf"
echo ""

# Multi-file Template (with imports)
echo "5. Multi-file Template"
echo "----------------------"
curl -s -X POST "$BASE_URL/render" \
  -H "Content-Type: application/json" \
  -d '{
    "template": {
      "main": "main.typ",
      "files": {
        "main.typ": "#import \"components.typ\": header, footer, card\n#import \"styles.typ\": *\n\n#set page(paper: \"a4\", margin: 2cm, header: header(), footer: footer())\n#set text(font: \"Inter\", size: 11pt)\n\n= Company Report\n\n#card(\"Revenue\", \"$1.2M\", \"up\")\n#card(\"Users\", \"45,231\", \"up\")\n#card(\"Growth\", \"23%\", \"up\")",
        "components.typ": "#let header() = [\n  #align(right)[#text(size: 9pt, fill: gray)[DocuForge Inc. | Confidential]]\n  #line(length: 100%, stroke: 0.5pt + gray)\n]\n\n#let footer() = [\n  #line(length: 100%, stroke: 0.5pt + gray)\n  #align(center)[#text(size: 9pt)[Page #counter(page).display() of #locate(loc => counter(page).final(loc).first())]]\n]\n\n#let card(title, value, trend) = {\n  box(width: 100%, inset: 12pt, fill: luma(245), radius: 4pt)[\n    #text(size: 10pt, fill: gray)[#title]\n    #v(4pt)\n    #text(size: 20pt, weight: \"bold\")[#value]\n    #h(8pt)\n    #text(size: 12pt, fill: if trend == \"up\" { green } else { red })[#if trend == \"up\" [\u2191] else [\u2193]]\n  ]\n  #v(8pt)\n}",
        "styles.typ": "#let primary = rgb(\"#2563eb\")\n#let secondary = rgb(\"#64748b\")\n#let success = rgb(\"#22c55e\")\n#let danger = rgb(\"#ef4444\")"
      }
    }
  }' \
  --output "$OUTPUT_DIR/04-multifile.pdf"
echo "Generated: $OUTPUT_DIR/04-multifile.pdf"
echo ""

# Table with Many Rows
echo "6. Large Table"
echo "--------------"
curl -s -X POST "$BASE_URL/render" \
  -H "Content-Type: application/json" \
  -d '{
    "template": {
      "main": "main.typ",
      "files": {
        "main.typ": "#let d = sys.inputs\n#set page(paper: \"a4\", margin: 1.5cm)\n\n= Sales Report\n\n#table(\n  columns: (auto, 1fr, auto, auto, auto),\n  inset: 6pt,\n  align: (center, left, left, right, right),\n  fill: (_, y) => if y == 0 { luma(230) } else if calc.odd(y) { luma(245) } else { white },\n  [*ID*], [*Product*], [*Category*], [*Qty*], [*Revenue*],\n  ..d.sales.map(s => (\n    s.id,\n    s.product,\n    s.category,\n    str(s.quantity),\n    [\\$#s.revenue]\n  )).flatten()\n)\n\n#v(1cm)\n#align(right)[*Total Revenue: \\$#d.total_revenue*]"
      }
    },
    "data": {
      "sales": [
        {"id": "001", "product": "Laptop Pro 15", "category": "Electronics", "quantity": 45, "revenue": 67500},
        {"id": "002", "product": "Wireless Mouse", "category": "Accessories", "quantity": 230, "revenue": 6900},
        {"id": "003", "product": "USB-C Hub", "category": "Accessories", "quantity": 180, "revenue": 10800},
        {"id": "004", "product": "Monitor 27\"", "category": "Electronics", "quantity": 67, "revenue": 26800},
        {"id": "005", "product": "Keyboard Mechanical", "category": "Accessories", "quantity": 120, "revenue": 14400},
        {"id": "006", "product": "Webcam HD", "category": "Electronics", "quantity": 95, "revenue": 9500},
        {"id": "007", "product": "Headphones Pro", "category": "Audio", "quantity": 78, "revenue": 23400},
        {"id": "008", "product": "Microphone USB", "category": "Audio", "quantity": 45, "revenue": 6750},
        {"id": "009", "product": "Desk Stand", "category": "Furniture", "quantity": 89, "revenue": 8900},
        {"id": "010", "product": "Cable Management Kit", "category": "Accessories", "quantity": 200, "revenue": 4000}
      ],
      "total_revenue": 178950
    }
  }' \
  --output "$OUTPUT_DIR/05-large-table.pdf"
echo "Generated: $OUTPUT_DIR/05-large-table.pdf"
echo ""

# Resume/CV Template
echo "7. Resume/CV Template"
echo "---------------------"
curl -s -X POST "$BASE_URL/render" \
  -H "Content-Type: application/json" \
  -d '{
    "template": {
      "main": "main.typ",
      "files": {
        "main.typ": "#let d = sys.inputs\n#set page(paper: \"a4\", margin: (x: 2cm, y: 1.5cm))\n#set text(font: \"Inter\", size: 10pt)\n\n#align(center)[\n  #text(size: 24pt, weight: \"bold\")[#d.name]\n  #v(4pt)\n  #text(size: 11pt)[#d.title]\n  #v(4pt)\n  #text(size: 9pt, fill: gray)[#d.email | #d.phone | #d.location]\n]\n\n#v(0.5cm)\n#line(length: 100%, stroke: 0.5pt)\n\n== Experience\n#for job in d.experience [\n  #v(8pt)\n  #grid(columns: (1fr, auto),\n    [*#job.title* at *#job.company*],\n    [#text(fill: gray)[#job.dates]]\n  )\n  #text(size: 9pt, fill: gray)[#job.location]\n  #v(4pt)\n  #for point in job.points [\n    - #point\n  ]\n]\n\n#v(0.5cm)\n== Education\n#for edu in d.education [\n  #v(4pt)\n  #grid(columns: (1fr, auto),\n    [*#edu.degree* - #edu.school],\n    [#text(fill: gray)[#edu.year]]\n  )\n]\n\n#v(0.5cm)\n== Skills\n#d.skills.join(\" | \")"
      }
    },
    "data": {
      "name": "Jane Smith",
      "title": "Senior Software Engineer",
      "email": "jane@example.com",
      "phone": "+1 (555) 123-4567",
      "location": "San Francisco, CA",
      "experience": [
        {
          "title": "Senior Software Engineer",
          "company": "Tech Corp",
          "location": "San Francisco, CA",
          "dates": "2021 - Present",
          "points": [
            "Led development of microservices architecture serving 10M+ users",
            "Reduced API response time by 40% through optimization",
            "Mentored team of 5 junior developers"
          ]
        },
        {
          "title": "Software Engineer",
          "company": "StartupXYZ",
          "location": "New York, NY",
          "dates": "2018 - 2021",
          "points": [
            "Built real-time data pipeline processing 1M events/day",
            "Implemented CI/CD reducing deployment time by 60%"
          ]
        }
      ],
      "education": [
        {"degree": "M.S. Computer Science", "school": "Stanford University", "year": "2018"},
        {"degree": "B.S. Computer Science", "school": "UC Berkeley", "year": "2016"}
      ],
      "skills": ["Rust", "Python", "TypeScript", "Kubernetes", "AWS", "PostgreSQL", "Redis"]
    }
  }' \
  --output "$OUTPUT_DIR/06-resume.pdf"
echo "Generated: $OUTPUT_DIR/06-resume.pdf"
echo ""

# Letter Template
echo "8. Business Letter"
echo "------------------"
curl -s -X POST "$BASE_URL/render" \
  -H "Content-Type: application/json" \
  -d '{
    "template": {
      "main": "main.typ",
      "files": {
        "main.typ": "#let d = sys.inputs\n#set page(paper: \"us-letter\", margin: (x: 2.5cm, y: 2cm))\n#set text(font: \"Inter\", size: 11pt)\n#set par(justify: true)\n\n#align(right)[\n  #d.sender.name\\\n  #d.sender.address\\\n  #d.sender.city\n]\n\n#v(1cm)\n\n#d.date\n\n#v(1cm)\n\n#d.recipient.name\\\n#d.recipient.title\\\n#d.recipient.company\\\n#d.recipient.address\n\n#v(1cm)\n\nDear #d.recipient.name,\n\n#v(0.5cm)\n\n#d.body\n\n#v(1cm)\n\nSincerely,\n\n#v(1.5cm)\n\n#d.sender.name\\\n#d.sender.title"
      }
    },
    "data": {
      "sender": {
        "name": "John Doe",
        "title": "CEO",
        "address": "123 Business Lane",
        "city": "San Francisco, CA 94102"
      },
      "recipient": {
        "name": "Jane Smith",
        "title": "Director of Operations",
        "company": "Acme Corporation",
        "address": "456 Corporate Blvd, New York, NY 10001"
      },
      "date": "January 15, 2024",
      "body": "I am writing to formally confirm our partnership agreement as discussed in our recent meeting. We are excited about the opportunity to work together and believe this collaboration will bring significant value to both organizations.\n\nAs outlined in our proposal, we will provide comprehensive software development services including system architecture design, implementation, and ongoing support. Our team is committed to delivering high-quality solutions that meet your specific requirements.\n\nPlease find the attached contract for your review. We kindly request that you sign and return the document by January 30, 2024. Should you have any questions or require clarification on any points, please do not hesitate to contact me directly."
    }
  }' \
  --output "$OUTPUT_DIR/07-letter.pdf"
echo "Generated: $OUTPUT_DIR/07-letter.pdf"
echo ""

# Error Handling Demo
echo "9. Error Handling (Syntax Error)"
echo "---------------------------------"
response=$(curl -s -X POST "$BASE_URL/render" \
  -H "Content-Type: application/json" \
  -d '{
    "template": {
      "main": "main.typ",
      "files": {
        "main.typ": "This has an #[unclosed bracket"
      }
    }
  }')
echo "$response" | jq .
echo ""

echo "10. Error Handling (Missing Variable)"
echo "--------------------------------------"
response=$(curl -s -X POST "$BASE_URL/render" \
  -H "Content-Type: application/json" \
  -d '{
    "template": {
      "main": "main.typ",
      "files": {
        "main.typ": "Hello #sys.inputs.undefined_variable"
      }
    }
  }')
echo "$response" | jq .
echo ""

# Custom Timeout Demo
echo "11. Custom Timeout Option"
echo "-------------------------"
curl -s -X POST "$BASE_URL/render" \
  -H "Content-Type: application/json" \
  -d '{
    "template": {
      "main": "main.typ",
      "files": {
        "main.typ": "Quick render with custom timeout"
      }
    },
    "options": {
      "timeout_ms": 3000
    }
  }' \
  --output "$OUTPUT_DIR/08-custom-timeout.pdf"
echo "Generated: $OUTPUT_DIR/08-custom-timeout.pdf"
echo ""

echo "=========================================="
echo "Demo Complete!"
echo "=========================================="
echo ""
echo "Generated PDFs:"
ls -la "$OUTPUT_DIR"/*.pdf
echo ""
echo "View PDFs with: xdg-open $OUTPUT_DIR/01-hello-world.pdf"
