export const fixtures = {
  user: { id: "usr_test", email: "test@docuforge.dev", plan: "free" as const },
  token: "test-jwt",
  apiKey: {
    raw_key: "docu_live_test_123",
    prefix: "docu_live_test",
    name: "Test Key",
    note: "Local testing",
  },
  templates: [
    {
      id: "tpl_1",
      name: "Invoice",
      description: "Invoice template",
      is_official: false,
      live_version: {
        id: "ver_1",
        version_number: 1,
        source: "#set page()",
        files: null,
        defaults: { invoice_id: "1234" },
        commit_message: "Initial",
        created_at: 1738377600,
      },
      created_at: 1738377600,
      updated_at: 1738377600,
    },
    {
      id: "tpl_official",
      name: "Official Report",
      description: "Official template",
      is_official: true,
      live_version: {
        id: "ver_official",
        version_number: 1,
        source: "#set page()",
        files: null,
        defaults: null,
        commit_message: "Initial",
        created_at: 1738377600,
      },
      created_at: 1738377600,
      updated_at: 1738377600,
    },
  ],
  templateDetail: {
    id: "tpl_1",
    name: "Invoice",
    description: "Invoice template",
    is_official: false,
    live_version: {
      id: "ver_1",
      version_number: 1,
      source: "#set page()",
      files: { "utils.typ": "#let x = 1" },
      defaults: { invoice_id: "1234" },
      commit_message: "Initial",
      created_at: 1738377600,
    },
    versions: [
      {
        id: "ver_1",
        version_number: 1,
        commit_message: "Initial",
        created_at: 1738377600,
      },
    ],
    created_at: 1738377600,
    updated_at: 1738377600,
  },
  templateVersionDetail: {
    id: "ver_1",
    version_number: 1,
    source: "#set page()",
    files: { "main.typ": "#set page()" },
    defaults: { invoice_id: "1234" },
    commit_message: "Initial",
    created_at: 1738377600,
  },
  usage: {
    plan: "free",
    renders: { used: 42, limit: 1000, remaining: 958 },
    period: { start: "2026-02-01", end: "2026-02-28" },
  },
  apiKeys: [
    {
      id: "key_1",
      prefix: "docu_live_test",
      name: "Production",
      last_used_at: 1738377600,
      created_at: 1738377600,
    },
  ],
  assets: [
    {
      id: "asset_1",
      name: "logo.png",
      mime_type: "image/png",
      size_bytes: 2048,
      hash: "hash",
      created_at: 1738377600,
    },
  ],
};
